version: '3.8'

services:
  mautic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mautic-app
    ports:
      - "80:80"
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME:-mautic}
      - MAUTIC_DB_USER=${MAUTIC_DB_USER:-mautic}
      - MAUTIC_DB_PASSWORD=${MAUTIC_DB_PASSWORD}
      - MAUTIC_DB_PREFIX=${MAUTIC_DB_PREFIX:-}
      - MAUTIC_ADMIN_USERNAME=${MAUTIC_ADMIN_USERNAME:-admin}
      - MAUTIC_ADMIN_PASSWORD=${MAUTIC_ADMIN_PASSWORD:-Maut1cR0cks!}
      - MAUTIC_ADMIN_EMAIL=${MAUTIC_ADMIN_EMAIL}
      - MAUTIC_ADMIN_FIRSTNAME=${MAUTIC_ADMIN_FIRSTNAME:-Admin}
      - MAUTIC_ADMIN_LASTNAME=${MAUTIC_ADMIN_LASTNAME:-User}
      - MAUTIC_MAILER_TRANSPORT=${MAUTIC_MAILER_TRANSPORT:-smtp}
      - MAUTIC_MAILER_HOST=${MAUTIC_MAILER_HOST}
      - MAUTIC_MAILER_PORT=${MAUTIC_MAILER_PORT:-587}
      - MAUTIC_MAILER_USER=${MAUTIC_MAILER_USER}
      - MAUTIC_MAILER_PASSWORD=${MAUTIC_MAILER_PASSWORD}
      - MAUTIC_MAILER_ENCRYPTION=${MAUTIC_MAILER_ENCRYPTION:-tls}
      - MAUTIC_MAILER_AUTH_MODE=${MAUTIC_MAILER_AUTH_MODE:-login}
      - MAUTIC_SITE_URL=${MAUTIC_SITE_URL}
      - MAUTIC_SECRET_KEY=${MAUTIC_SECRET_KEY}
      - MAUTIC_REQUEST_CONTEXT_HOST=${MAUTIC_REQUEST_CONTEXT_HOST}
      - MAUTIC_REQUEST_CONTEXT_SCHEME=${MAUTIC_REQUEST_CONTEXT_SCHEME:-https}
      - MAUTIC_TRUSTED_HOSTS=${MAUTIC_TRUSTED_HOSTS}
      - MAUTIC_TRUSTED_PROXIES=${MAUTIC_TRUSTED_PROXIES}
    volumes:
      - mautic_media:/var/www/html/media
      - mautic_var:/var/www/html/var
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - mautic-network

  db:
    image: mariadb:10.11
    container_name: mautic-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MAUTIC_DB_NAME:-mautic}
      - MYSQL_USER=${MAUTIC_DB_USER:-mautic}
      - MYSQL_PASSWORD=${MAUTIC_DB_PASSWORD}
    volumes:
      - mautic_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=1073741824
    networks:
      - mautic-network

volumes:
  mautic_db_data:
    driver: local
  mautic_media:
    driver: local
  mautic_var:
    driver: local

networks:
  mautic-network:
    driver: bridge
